name = "a-to-z-bot"
main = "src/worker.mjs"
compatibility_date = "2025-05-15"
account_id = "573e3fe530393bbde84dc5227e2ae9fd"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.